
server:
  port: 8061
  

spring:
  application:
    name: ksdemo
    
  cloud:
    stream:
      function:        definition: log;count;logcount
      bindings:
        voteOut:
          destination: event.vote
          producer:
            header-mode: headers            use-native-encoding: true
        log-in-0:
          destination: event.vote
          group: loggers
          consumer:            header-mode: headers
        count-in-0:
          destination: event.vote
          group: counters
          consumer:            header-mode: headers
            use-native-decoding: true
        count-out-0:
          destination: event.vote.count
          producer:            header-mode: headers
            use-native-encoding: true
        logcount-in-0:
          destination: event.vote.count
          consumer:            header-mode: headers
            use-native-decoding: true
      kafka:
        bindings:          voteOut:
            producer:              configuration:
                key.serializer: org.apache.kafka.common.serialization.StringSerializer
                value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
        binder:
          brokers:
          - ubuntuvm:9094
        streams:
          bindings:
            count-in-0:
              consumer:                key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value-serde: org.springframework.kafka.support.serializer.JsonSerde            count-out-0:
              producer:                key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
            logcount-in-0:
              consumer:                key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value-serde: org.apache.kafka.common.serialization.Serdes$LongSerde
          binder:
            brokers:
            - ubuntuvm:9094
            functions:
              log:
                application-id: logapp              count:
                application-id: countapp
              logcount:
                application-id: logcountapp
            deserialization-exception-handler: logandfail
            configuration:
              commit.interval.ms: 1000
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              spring.json.trusted.packages: '*'